[package]
name = "game_render"
version = "0.1.0"
edition = "2021"

[dependencies]
game_window = { version = "0.1.0", path = "../game_window" }

bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
bytemuck = { version = "1.13.1", features = ["derive"] }
futures-lite = "1.13.0"
glam = { version = "0.24.0", features = ["bytemuck"] }
pretty_env_logger = "0.4.0"
tracing = { version = "0.1.37", features = ["log-always"] }
wgpu = "0.16.0"
image = "0.24.6"
