[package]
name = "game_render"
version = "0.1.0"
edition = "2021"

[dependencies]
ab_glyph = "0.2.21"
bytemuck = { version = "1.13.1", features = ["derive"] }
glam = "0.24.0"
image = "0.24.6"
tokio = { version = "1.28.0", features = ["rt"] }
tracing = "0.1.37"
wgpu = "0.16.0"
winit = "0.28.3"
