[package]
name = "game_render"
version = "0.1.0"
edition = "2021"

[dependencies]
game_window = { version = "0.1.0", path = "../game_window" }
game_common = { versionr = "0.1.0", path = "../game_common" }
game_asset = { version = "0.1.0", path = "../game_asset" }
game_core = { version = "0.1.0", path = "../game_core" }

bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
bytemuck = { version = "1.13.1", features = ["derive"] }
futures-lite = "1.13.0"
glam = { version = "0.24.0", features = ["bytemuck"] }
tracing = { version = "0.1.37", features = ["log-always"] }
wgpu = "0.16.0"
image = "0.24.6"
parking_lot = "0.12.1"
