[package]
name = "game_physics"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
bevy_ecs = "0.10.0"
game_common = { version = "0.1.0", path = "../game_common" }

rapier3d = "0.17.2"
tracing = "0.1.37"
