[package]
name = "game_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
game_common = { version = "0.1.0", path = "../game_common" }
game_core = { version = "0.1.0", path = "../game_core" }
game_input = { version = "0.1.0", path = "../game_input" }
game_ui = { version = "0.1.0", path = "../game_ui", features = ["editor"] }

bevy = "0.9.1"
bevy_egui = "0.19.0"
