[workspace]
members = [
    "game_ai",
    "game_audio",
    "game_core",
    "game_common",
    "game_client",
    "game_server",
    "game_ui",
    "game_net",
    "game_input",
    "game_macros",
    "game_editor",
    "game_physics",
    "game_data",
    "game_script",
    "game_wasm",
    "game_render",
    "game_window",
    "game_asset",
    "game_gltf",
    "game_ui_macros",
    "game_ui_macros_test",
    "tests",
]

resolver = "2"
