[workspace]
members = [
    "game_ai",
    "game_audio",
    "game_core",
    "game_common",
    "game_client",
    "game_server",
    "game_ui",
    "game_net",
    "game_input",
    "game_macros",
    "game_editor",
    "game_physics",
    "game_api",
]

resolver = "2"
