[advisories]
vulnerability = "warn"
unmaintained = "warn"
notice = "warn"
unsound = "warn"

[bans]
multiple-versions = "warn"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
copyleft = "allow"
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "BSD-2-Clause", "ISC", "CC0-1.0", "Zlib", "Apache-2.0 WITH LLVM-exception"]

exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]
