[package]
name = "game_data"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
game_common = { version = "0.1.0", path = "../game_common" }
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["fs"] }
tracing = "0.1.37"
