[package]
name = "game_crash_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
game_macros = { version = "0.1.0", path = "../game_macros" }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29.0", features = ["signal"] }

[lints]
workspace = true
