[package]
name = "game_ui_macros_test"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
game_ui = { version = "0.1.0", path = "../game_ui" }
