[package]
name = "game_audio"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[features]
default = []

[dependencies]
bevy_ecs = "0.9.1"
bevy_app = "0.9.1"
bevy_reflect = "0.9.1"
bevy_asset = "0.9.1"

kira = { version = "0.7.1", features = ["cpal"] }
parking_lot = "0.12.1"
tracing = "0.1.37"
glam = "0.22.0"
