[package]
name = "game_audio"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[features]
default = []

[dependencies]
bevy_ecs = "0.10"
bevy_app = "0.10.0"

tracing = "0.1.37"
glam = "0.23.0"
cpal = "0.15.2"
