[package]
name = "game_gltf"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
bytes = "1.4.0"
game_render = { version = "0.1.0", path = "../game_render" }
glam = "0.24.0"

gltf = "1.1.0"
indexmap = "1.9.3"
tracing = "0.1.37"
