[package]
name = "game_worldgen"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
game_wasm = { version = "0.1.0", path = "../game_wasm" }

serde = { version = "1.0.204", features = ["derive"], optional = true }
bincode = "1.3.3"
glam = "0.28.0"
