[package]
name = "game_worldgen"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[features]
default = ["json"]
# Enable loading of the JSON format.
json = ["dep:serde", "dep:serde_json"]

[lints]
workspace = true

[dependencies]
base64 = "0.22.1"
bytes = "1.6.0"
game_common = { version = "0.1.0", path = "../game_common" }
glam = "0.28.0"
image = "0.25.1"

serde = { version = "1.0.204", features = ["derive"], optional = true }
serde_json = { version = "1.0.120", optional = true }
