[package]
name = "weapon_reload"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lib]
crate-type = ["cdylib"]

[dependencies]
game_wasm = { version = "0.1.0", path = "../../../../game_wasm" }
shared = { version = "0.1.0", path = "../shared" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
