[package]
name = "builder"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }

[lints]
workspace = true
