[package]
name = "builder"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
pretty_env_logger = "0.5.0"
log = "0.4.22"
thiserror = "1.0.64"
tar = "0.4.42"
flate2 = "1.0.34"

[lints]
workspace = true
