[package]
name = "json2dat"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
game_common = { version = "0.1.0", path = "../../game_common" }
game_data = { version = "0.1.0", path = "../../game_data" }

clap = { version = "4.3.17", features = ["derive"] }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
