use std::str::FromStr;

use game_common::collections::string::SmallStr;

use crate::ButtonState;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct KeyboardInput {
    pub scan_code: ScanCode,
    pub key_code: Option<KeyCode>,
    // TODO: Maybe add a dedicated "NamedKey" type instead of
    // raw text.
    pub text: Option<SmallStr>,
    pub state: ButtonState,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub struct ScanCode(pub u32);

#[derive(Copy, Clone, Debug, PartialEq, Eq, Hash)]
pub enum KeyCode {
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    Snapshot,
    Scroll,
    Pause,
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    Left,
    Up,
    Right,
    Down,
    Back,
    Return,
    Space,
    Compose,
    Caret,
    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,
    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LSuper,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    NavigateForward,
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RSuper,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

impl KeyCode {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Key1 => "1",
            Self::Key2 => "2",
            Self::Key3 => "3",
            Self::Key4 => "4",
            Self::Key5 => "5",
            Self::Key6 => "6",
            Self::Key7 => "7",
            Self::Key8 => "8",
            Self::Key9 => "9",
            Self::Key0 => "0",
            Self::A => "A",
            Self::B => "B",
            Self::C => "C",
            Self::D => "D",
            Self::E => "E",
            Self::F => "F",
            Self::G => "G",
            Self::H => "H",
            Self::I => "I",
            Self::J => "J",
            Self::K => "K",
            Self::L => "L",
            Self::M => "M",
            Self::N => "N",
            Self::O => "O",
            Self::P => "P",
            Self::Q => "Q",
            Self::R => "R",
            Self::S => "S",
            Self::T => "T",
            Self::U => "U",
            Self::V => "V",
            Self::X => "X",
            Self::Y => "Y",
            Self::Z => "Z",
            Self::F1 => "F1",
            Self::F2 => "F2",
            Self::F3 => "F3",
            Self::F4 => "F4",
            Self::F5 => "F5",
            Self::F6 => "F6",
            Self::F7 => "F7",
            Self::F8 => "F8",
            Self::F9 => "F9",
            Self::F10 => "F10",
            Self::F11 => "F11",
            Self::F12 => "F12",
            Self::F13 => "F13",
            Self::F14 => "F14",
            Self::F15 => "F15",
            Self::F16 => "F16",
            Self::F17 => "F17",
            Self::F18 => "F18",
            Self::F19 => "F19",
            Self::F20 => "F20",
            Self::F21 => "F21",
            Self::F22 => "F22",
            Self::F23 => "F23",
            Self::F24 => "F24",
            Self::Escape => "Escape",
            Self::Space => "Space",
            Self::Numpad0 => "Numpad0",
            Self::Numpad1 => "Numpad1",
            Self::Numpad2 => "Numpad2",
            Self::Numpad3 => "Numpad3",
            Self::Numpad4 => "Numpad4",
            Self::Numpad5 => "Numpad5",
            Self::Numpad6 => "Numpad6",
            Self::Numpad7 => "Numpad7",
            Self::Numpad8 => "Numpad8",
            Self::Numpad9 => "Numpad9",
            Self::Tab => "Tab",
            _ => todo!(),
        }
    }

    fn try_from_str(s: &str) -> Option<Self> {
        match s {
            "1" => Some(Self::Key1),
            "2" => Some(Self::Key2),
            "3" => Some(Self::Key3),
            "4" => Some(Self::Key4),
            "5" => Some(Self::Key5),
            "6" => Some(Self::Key6),
            "7" => Some(Self::Key7),
            "8" => Some(Self::Key8),
            "9" => Some(Self::Key9),
            "0" => Some(Self::Key0),
            "A" | "a" => Some(Self::A),
            "B" | "b" => Some(Self::B),
            "C" | "c" => Some(Self::C),
            "D" | "d" => Some(Self::D),
            "E" | "e" => Some(Self::E),
            "F" | "f" => Some(Self::F),
            "G" | "g" => Some(Self::G),
            "H" | "h" => Some(Self::H),
            "I" | "i" => Some(Self::I),
            "J" | "j" => Some(Self::J),
            "K" | "k" => Some(Self::K),
            "L" | "l" => Some(Self::L),
            "M" | "m" => Some(Self::M),
            "N" | "n" => Some(Self::N),
            "O" | "o" => Some(Self::O),
            "P" | "p" => Some(Self::P),
            "Q" | "q" => Some(Self::Q),
            "R" | "r" => Some(Self::R),
            "S" | "s" => Some(Self::S),
            "T" | "t" => Some(Self::T),
            "U" | "u" => Some(Self::U),
            "V" | "v" => Some(Self::V),
            "W" | "w" => Some(Self::W),
            "X" | "x" => Some(Self::X),
            "Y" | "y" => Some(Self::Y),
            "Z" | "z" => Some(Self::Z),
            "F1" | "f1" => Some(Self::F1),
            "F2" | "f2" => Some(Self::F2),
            "F3" | "f3" => Some(Self::F3),
            "F4" | "f4" => Some(Self::F4),
            "F5" | "f5" => Some(Self::F5),
            "F6" | "f6" => Some(Self::F6),
            "F7" | "f7" => Some(Self::F7),
            "F8" | "f8" => Some(Self::F8),
            "F9" | "f9" => Some(Self::F9),
            "F10" | "f10" => Some(Self::F10),
            "F11" | "f11" => Some(Self::F11),
            "F12" | "f12" => Some(Self::F12),
            "F13" | "f13" => Some(Self::F13),
            "F14" | "f14" => Some(Self::F14),
            "F15" | "f15" => Some(Self::F15),
            "F16" | "f16" => Some(Self::F16),
            "F17" | "f17" => Some(Self::F17),
            "F18" | "f18" => Some(Self::F18),
            "F19" | "f19" => Some(Self::F19),
            "F20" | "f20" => Some(Self::F20),
            "F21" | "f21" => Some(Self::F21),
            "F22" | "f22" => Some(Self::F22),
            "F23" | "f23" => Some(Self::F23),
            "F24" | "f24" => Some(Self::F24),
            "Space" | "space" => Some(Self::Space),
            "Escape" | "escape" => Some(Self::Escape),
            "Tab" | "tab" => Some(Self::Tab),
            "Numpad0" | "numpad0" => Some(Self::Numpad0),
            "Numpad1" | "numpad1" => Some(Self::Numpad1),
            "Numpad2" | "numpad2" => Some(Self::Numpad2),
            "Numpad3" | "numpad3" => Some(Self::Numpad3),
            "Numpad4" | "numpad4" => Some(Self::Numpad4),
            "Numpad5" | "numpad5" => Some(Self::Numpad5),
            "Numpad6" | "numpad6" => Some(Self::Numpad6),
            "Numpad7" | "numpad7" => Some(Self::Numpad7),
            "Numpad8" | "numpad8" => Some(Self::Numpad8),
            "Numpad9" | "numpad9" => Some(Self::Numpad9),
            _ => None,
        }
    }
}

#[derive(Copy, Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct InvalidKeyCode;

impl FromStr for KeyCode {
    type Err = InvalidKeyCode;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Self::try_from_str(s).ok_or(InvalidKeyCode)
    }
}
