[package]
name = "game_input"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
bevy_ecs = "0.10.0"
bevy_app = "0.10.0"
glam = "0.24.0"
winit = "0.28.5"
