[package]
name = "slangc"
version = "0.1.0"
edition = "2024"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
thiserror = "2.0.12"
rand = "0.9.1"
tracing = "0.1.41"

[[test]]
name = "compile"
path = "tests/compile.rs"
