[package]
name = "game_asset"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
futures = "0.3.28"
parking_lot = "0.12.1"
slotmap = "1.0.6"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["full"] }
