[package]
name = "game_asset"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
futures = "0.3.28"
parking_lot = "0.12.1"
slotmap = "1.0.6"
tokio = { version = "1.28.1", features = ["full"] }
