[package]
name = "game_asset"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
futures = "0.3.30"
parking_lot = "0.12.3"
slotmap = "1.0.7"
tokio = { version = "1.38.0", features = ["full"] }
