[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
bevy_ecs = "0.9.1"
glam = "0.22.0"
hex = "0.4.3"
