[package]
name = "make"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
log = "0.4.22"
pretty_env_logger = "0.5.0"
