[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
ai = { version = "*", path = "../ai" }
common = { version = "*", path = "../common" }

bevy = "0.9.1"
bevy_ecs = "0.9.1"
tracing = "0.1.37"
