[package]
name = "game_window"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
game_input = { version = "0.1.0", path = "../game_input" }

bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
glam = "0.24.0"
winit = "0.28.4"
tracing = "0.1.37"
raw-window-handle = "0.5.2"
parking_lot = "0.12.1"
