[package]
name = "game_window"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[lints]
workspace = true

[dependencies]
game_common = { version = "0.1.0", path = "../game_common" }
game_input = { version = "0.1.0", path = "../game_input" }
game_tracing = { version = "0.1.0", path = "../game_tracing" }

glam = "0.28.0"
winit = "0.29.4"
tracing = "0.1.40"
raw-window-handle = "0.6.0"
parking_lot = "0.12.3"
