[package]
name = "game_ui"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[features]
default = []

[dependencies]
game_common = { version = "0.1.0", path = "../game_common" }
game_input = { version = "0.1.0", path = "../game_input" }
game_render = { version = "0.1.0", path = "../game_render" }
game_window = { version = "0.1.0", path = "../game_window" }

game_ui_view = { version = "0.1.0", path = "../game_ui_view" }

bevy_ecs = "0.10.0"
bevy_app = "0.10.0"
glam = "0.24.0"
ab_glyph = "0.2.21"
image = "0.24.6"
wgpu = "0.16.0"
bytemuck = "1.13.1"

# TODO: This should go throught `game_window` instead.
winit = "0.28.5"
parking_lot = "0.12.1"
slotmap = "1.0.6"
tracing = "0.1.37"
pretty_env_logger = "0.5.0"
