[package]
name = "game_ui"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
game_common = { version = "0.1.0", path = "../game_common" }
game_input = { version = "0.1.0", path = "../game_input" }

bevy = "0.9.1"
bevy_ecs = "0.9.1"
bevy_egui = "0.18.0"
