[package]
name = "game_client"
version = "0.1.0"
edition = "2021"
authors = ["MrGunflame <git@robbsrv.de>"]
license = "GPL-3.0-or-later"

[dependencies]
game_ai = { version = "0.1.0", path = "../game_ai" }
game_common = { version = "0.1.0", path = "../game_common" }
game_core = { version = "0.1.0", path = "../game_core" }
game_ui = { version = "0.1.0", path = "../game_ui" }
game_input = { version = "0.1.0", path = "../game_input" }
game_audio = { version = "0.1.0", path = "../game_audio" }
game_net = { version = "0.1.0", path = "../game_net" }

ahash = "0.8.2"
bevy = { version = "0.10.0", features = ["wav", "jpeg"] }
serde = { version = "1.0.149", features = ["derive"], optional = true }
bevy_egui = "0.17"
winit = "0.27.5"
tracing = "0.1.37"
chrono = "0.4.23"
nalgebra = "0.31.4"
noise = "0.8.2"
tokio = { version = "1.25.0", features = ["full"] }
clap = { version = "4.1.6", features = ["derive"] }
parking_lot = "0.12.1"

[features]
default = []


# dylib bevy for dev
dynamic = ["bevy/dynamic_linking"]

serde = ["dep:serde"]

[profile.release]
debug-assertions = true
opt-level = 3
lto = "fat"
codegen-units = 1

[profile.dev.package.bevy]
opt-level = 3

[profile.dev.package.bevy_rapier3d]
opt-level = 3
