name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  RUSTFLAGS: -Awarnings
  RUST_BACKTRACE: full
  nightly: nightly-2023-08-12

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable --no-self-update && rustup default stable
    - run: cargo fmt --all --check

  stable:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable --no-self-update && rustup default stable
    - run: cargo test --workspace

  miri:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update $nightly --no-self-update && rustup default $nightly
    - run: cargo miri test --workspace

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup update stable --no-self-update && rustup default stable
    - run: cargo doc --no-deps --all-features
